### ISSUE TITLE
Read fuel price from internet

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/trip-o-meter#2]
Petrol prices for each state capital in India can be read from below API.

https://tripometer.now.sh

Developed by @RaghuChandrasekaran

**Comment by midhunhk** [comment]
Data will be returned in below JSON format.

[
	{
		city: "Agartala",
		price: "64.20"
	},
	{
		city: "Aizwal",
		price: "64.46"
	},
	{
		city: "Ambala",
		price: "68.44"
	},
	{
		city: "Bengaluru",
		price: "73.92"
	},
	{
		city: "Bhopal",
		price: "76.17"
	},
	{
		city: "Bhubhaneswar",
		price: "69.05"
	},
	{
		city: "Chandigarh",
		price: "69.51"
	},
	{
		city: "Dehradun",
		price: "72.96"
	},
	{
		city: "Gandhinagar",
		price: "70.93"
	},
	{
		city: "Gangtok",
		price: "71.19"
	},
	{
		city: "Guwahati",
		price: "71.59"
	},
	{
		city: "Hyderabad",
		price: "73.57"
	},
	{
		city: "Imphal",
		price: "66.97"
	},
	{
		city: "Itanagar",
		price: "64.83"
	},
	{
		city: "Jaipur",
		price: "71.44"
	},
	{
		city: "Jammu",
		price: "71.02"
	},
	{
		city: "Jullunder",
		price: "74.20"
	},
	{
		city: "Kohima",
		price: "67.07"
	},
	{
		city: "Lucknow",
		price: "71.33"
	},
	{
		city: "Panjim",
		price: "62.77"
	},
	{
		city: "Patna",
		price: "71.47"
	},
	{
		city: "Pondicherry",
		price: "64.90"
	},
	{
		city: "Port Blair",
		price: "59.55"
	},
	{
		city: "Raipur",
		price: "69.85"
	},
	{
		city: "Ranchi",
		price: "70.21"
	},
	{
		city: "Shillong",
		price: "67.79"
	},
	{
		city: "Shimla",
		price: "69.96"
	},
	{
		city: "Srinagar",
		price: "73.78"
	},
	{
		city: "Trivandrum",
		price: "73.15"
	}
]

**Comment by RaghuChandrasekaran** [comment]
New repo has been created to maintain API and develop web version of Trip-o-meter.Deployments will be in Heroku as it is supported by travis.
https://github.com/RaghuChandrasekaran/trip-o-meter-web
https://tripometer.herokuapp.com/

**Comment by midhunhk** [comment]
How to create use the trip-o-meter-web API for fetching the fuel prices, 

Only the url for fetching status is present as per docs - https://tripometerdev.herokuapp.com/status

**Comment by RaghuChandrasekaran** [comment]
https://tripometer.herokuapp.com now has the latest version of the API.
trip-o-meter-api project is now deleted and both web and api is maintained in a single repo.

Web version of app is under development. 

**IMPORTANT**

Prod Version :  https://tripometer.herokuapp.com

Dev Version:  https://tripometerdev.herokuapp.com

**Comment by midhunhk** [comment]
Whats the difference between dev and prod versions?

**Comment by RaghuChandrasekaran** [comment]
Dev version will have the latest build of development branch and might have breaking changes.
But prod will always have the stable latest release.For public release we can use the prod version.

**Comment by RaghuChandrasekaran** [comment]
Dev version will have the latest build of development branch and might have breaking changes.
But prod will always have the stable latest release.For public release we can use the prod version.

**Comment by midhunhk** [comment]
Go it.

Prod is Stable Channel &
Dev is Canary :+1:

**Comment by midhunhk** [comment]
Metros:
https://tripometer.herokuapp.com/cost/IN/metro
States:
https://tripometer.herokuapp.com/cost/IN/state/Kerala

**Comment by RaghuChandrasekaran** [comment]
@midhunhk The API from which this data was scrapped has some issues now.We need to find a new source to get the fuel prices which is changing daily now.

**Comment by midhunhk** [comment]
Ok, Lets do some research on this.

**Comment by RaghuChandrasekaran** [comment]
Potential [API ](https://market.mashape.com/dreamsoft/indhan-daily-fuel-price-india/support) which we can use.But for basic plan we get two days old data only.For $1/Month we get daily updates.

The only other option is to scrap the information from a website.
