### ISSUE TITLE
Using Google maps API for calculating trip distance

### ISSUE THREAD

**Issue by RaghuChandrasekaran** [midhunhk/trip-o-meter#3]
Now trip distance is asked as an input from user.
Suggested feature is to ask for the destination and calculate the trip distance from current location.
This can be an optional feature so that users won't be deterred from using the app offline.

**Comment by midhunhk** [comment]
Try to see if we can use the below service from Google Maps API
https://developers.google.com/maps/documentation/directions

Sample request : 
https://maps.googleapis.com/maps/api/directions/json?origin=Toronto&destination=Montreal&key=YOUR_API_KEY

**Comment by midhunhk** [comment]
Closing as this is a Complex Requirement. Will reopen if its feasible to implement inf future
