### ISSUE TITLE
About screen changes background color of notification bar which makes icons unlegible

### ISSUE THREAD

**Issue by RaghuChandrasekaran** [midhunhk/trip-o-meter#4]
Screenshot:
![screenshot_2017-01-06-07-58-16-790_com ae apps tripmeter](https://cloud.githubusercontent.com/assets/7160211/21708117/4cc20444-d3fb-11e6-9338-92c9d7b6ade6.png)

**Comment by midhunhk** [comment]
Known issues in AboutActivity where status bar color is not getting set. Need to investigate more.
